### ISSUE TITLE
Java class hotswap not working in debug model

### ISSUE THREAD

**Issue by caiwenhn2008** [dansomething/coc-java-debug#34] opened 2022-03-26 13:09 UTC
**Describe the issue**
Hi,
Thanks for buiding this excellent extension to simplify our java debug in NVIM, I could have basic java debug in NVIM with limited configuration, cheers!!!

but i see java class hotswap function not working, is it not supported today?

I have set "let g:ycm_java_hotcodereplace_mode = 'always' as suggested from https://github.com/puremourning/vimspector#java

but it seems the java class cannot be hot-swapped in debug model.

See hotcodereplace message in vimspector log:
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/6037646/160241066-a1a5908d-b1e0-4607-beee-fa00846477c3.png">

2022-03-26 20:54:50,921 - DEBUG - Message received: {'event': 'hotcodereplace', 'body': {'changeType': 'BUILD_COMPLETE', 'message': 'Build completed.', 'type': 'hotcodereplace'}, 'seq': 21, 'type': 'event'}

**Comment by dansomething** [comment] 2022-03-26 13:37
I'll see if I can reproduce it, but it's most likely an issue with Vimspector or jdt.ls since this project does little more than provide some "glue" between the two.

What versions of the relevant software are you using?
vim/nvim:
coc.nvim:
coc-java:
vimspector:
java:
jdt.ls:

**Comment by dansomething** [comment] 2022-03-29 00:56
I can replicate the issue, but I still don't know the root cause. Though I'm sure it's either an issue in Vimspector or jdt.ls. I can't get it to work in VS Code either using the same example.

**Comment by dansomething** [comment] 2024-07-13 15:12
This should be fixed by #45

**Closed as completed** 2024-08-05 13:12 UTC
Labels: question
